version: "2"
run:
  concurrency: 6
  go: 1.22.5
linters:
  enable:
    - asciicheck
    - bidichk
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - dupl
    - dupword
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - grouper
    - inamedparam
    - interfacebloat
    - maintidx
    - misspell
    - mnd
    - nakedret
    - nestif
    - nlreturn
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - tagalign
    - testableexamples
    - testpackage
    - usestdlibvars
    - whitespace
    - wsl
  disable:
    - depguard
    - errcheck
    - godox
    - govet
    - lll
    - staticcheck
    - unused
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
severity:
  default: warning
formatters:
  enable:
    - gofmt
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
